### ISSUE TITLE
A question about NLSE

### ISSUE THREAD

**Issue by LoveUSimone** [Wulx2050/DeepXDE-and-PINN#1]
Hi!Thanks for your work!
I see a picture in your work but I don't find the code.So I want to know if I can get the code from you 
The picture is as follwing.Looking forward to your early reply.
![blob](https://user-images.githubusercontent.com/102349878/232784881-6d10398c-0613-4a27-b689-6dd058fb4885.jpg)

**Comment by Wulx2050** [comment]
from here:  https://github.com/maziarraissi/PINNs/tree/master/main/continuous_time_inference%20(Schrodinger)
